### ISSUE TITLE
Prediction always at 90.00% and shows infinite start loading indicator, if screen is switched

### ISSUE THREAD

**Issue by GaoMax** [st0nedB/rooms#13]
**Describe the bug**
The likelihood percentage is always at 90.00%, no matter in which room I am and if I switch between the screens (i.e. to Settings and back to Prediction), it shows Starting ...
I am using 10 ESP32s running ESPHome with iBeacon enabled with the same uuid and major, but different minors.

**Expected behavior**
The right likelihood percentage and not the starting loading indicator.
**Screenshots**
![IMG_1132](https://user-images.githubusercontent.com/18214226/111291640-af7df680-8647-11eb-9dd4-549d29fbe46d.PNG)
![IMG_1133](https://user-images.githubusercontent.com/18214226/111291653-b147ba00-8647-11eb-9baf-a8fd94d85454.PNG)

**Desktop (please complete the following information):**
 - OS: iOS 14.5 beta 4

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro

**Comment by GaoMax** [comment]
`            let predProb = round( Double( truncating: output.featureValue(for: "classProbability")!.dictionaryValue[AnyHashable(predRoom)]! )*1000)/10
            print("Room \(predRoom), Likelihood \(predProb)")
            //let predProb:Double = 90
            currentRoom = String(predRoom)
            
            // Update the UI Elements
            labelRoom.text = currentRoom
            labelPredictionLikelyhood.text = String(format: "%.2f %%", arguments: [predProb])
                
        
            // if the prediction probability exceeds a threshold, accept the prediction
            if (predProb > predictionThreshold*100 && currentRoom != String(predRoom) && !fakeMove) || currentRoom == "" {
                // update currentRoom
                // send to mqtt broker
                let json = ["room" : predRoom, "likelihood": predProb] as [String : Any]
                publishToMQTTServer(mqttConfig: self.mqttConfig, message: json)
                print("MQTT updated")
            }`

I fixed it by changing PredictionViewController!
Awesome project, really appreciate it. I've noticed that the background task something doesn't restart using the fake move. I'm currently investigating and will open a new Issue.

**Comment by GaoMax** [comment]
@st0nedB Could you push an update? I would make a merge request, but I've customized the code with personal information.

**Comment by st0nedB** [comment]
Done! Thanks @GaoMax for your investigations. It was actually an issue with code that was added for debugging in issue#3, but was never removed. I guess that's what happens when you review your branches after several months and think its a good idea to merge them. Sorry for the confusions!
