### ISSUE TITLE
MQTT not working

### ISSUE THREAD

**Issue by collinj22** [st0nedB/rooms#5]
Hi,

I was able to get the app installed and the predictions working but I am not able to get it to send the room updates to MQTT.

The MQTT connection test on the settings page works and I can see the test message. Also sometimes it seems to get stuck on the "Starting..." message and won't start predictions until I force close the app.

I am running the app on an iphone Xr with ios 14 using the master branch.

Any suggestions would be appreciated.

Thanks

**Comment by st0nedB** [comment]
Hey, thanks for opening an issue and testing the app. And sorry for the late reply.
There have been some major changes in the ML and MQTT implementation in the app. Also I haven't had time to look into iOS 14. 
Please try the #issue3 branch and let me know if the error persists.

**Comment by st0nedB** [comment]
Should be fixed with #3. Closing this for now.
